<?php
#C:\wamp\www\GitHub\createur-romans\fichiersDuProjet\assets\inc
require_once "../fichiersDuProjet/assets/inc/library01.inc.php";

$chaine = "Introduction

	Ah, ce que ça peux être ennuyeux! Je hait toutes les conférences où l\\\\\\\\\\\\\\\'on parle pour rien dire. Par chance, ce n\\\\\\\\\\\\\\\'est pas moi qui est au micro, je peux ainsi discrètement dormir. AAAAye! Oh, pardon! Je vous baillais en pleine face. Laissez-moi me présenter, je m\\\\\\\\\\\\\\\'appelle Véronik Chalopin et j\\\\\\\\\\\\\\\'ai un Baccalauréat en micro-biologie. En ce moment même, j\\\\\\\\\\\\\\\'étudie en neurologie animale. Ce qui me fait chier c\\\\\\\\\\\\\\\'est que je dois assister à cette foutue conférence parce que, bonace comme je suis, j\\\\\\\\\\\\\\\'ai pris la place de quelqu\\\\\\\\\\\\\\\'un, ça m\\\\\\\\\\\\\\\'apprendra à vouloir être trop bonne!

	La conférence est enfin terminée, vivement que je sois de retour à la maison. Voyez-vous, je suis non seulement intelligente (comme -toutes- les femmes d\\\\\\\\\\\\\\\'aujourd\\\\\\\\\\\\\\\'hui) et débrouillarde, mais aussi prompte et parfois directe au point d\\\\\\\\\\\\\\\'en être cruelle; cela m\\\\\\\\\\\\\\\'as valus le surnom de Véro la Gorgone. Remarquez, je le méritais bien, un vilain défaut de ce genre doit bien finir par être punit. Cela me rappelle ma copine archéologue : Niki Farfouille; sans oublier le fait qu\\\\\\\\\\\\\\\'elle est célèbre. Tiens, et... si je vous mettais dans le secret... oui, pourquoi pas? Et puis non, je vais plutôt vous raconter l\\\\\\\\\\\\\\\'aventure la plus incroyable qui ait pus m\\\\\\\\\\\\\\\'arriver.


	I. L\\\\\\\\\\\\\\\'Amazonie

	Philibert et moi étions en Amazonie pour compléter une étude que notre professeur Carl Sparks nous avais donné à faire en vu d\\\\\\\\\\\\\\\'avoir éventuellement nos diplômes. Bien sûr, nous avons réussis et de très belle façon en plus. Alors que nous ramassions nos effets personnels respectifs, nous avons entendu comme des détonations et maints cris que nous avons (de par nos études) déterminé comme appartenant aux sajous qui habitent la partie de la forêt proche de l\\\\\\\\\\\\\\\'endroit où nous avions établis notre camp. Nous n\\\\\\\\\\\\\\\'avons fait ni une, ni deux et nous avons couru en direction des détonations. Malheureusement pour nous, nous sommes arrivé trop tard et de par ce fait, nous n\\\\\\\\\\\\\\\'avons pus que constater les dommages produit par les braconniers. La scène recelait une telle horreur que je n\\\\\\\\\\\\\\\'ose encore m\\\\\\\\\\\\\\\'en rappeler : sur le sol humide baigné de lumière, gisait par dizaines les corps de petits singes d\\\\\\\\\\\\\\\'à peine un ou deux ans. Leurs parents furent enlevé et tué pour divers éléments de leurs physionomie animale. Philibert n\\\\\\\\\\\\\\\'eus autre réaction que de jurer de revenir ici et d\\\\\\\\\\\\\\\'arrêter les vilains, c\\\\\\\\\\\\\\\'était un geste très humain de sa part, mais pour moi, cette réaction ne me semble que masculine; pour ma part, je tomba tout simplement à genoux, complètement abattue par ce geste monstrueux, impardonnable, MAIS QUI M\\\\\\\\\\\\\\\'AS FOUTU DE PAREIL CONS!! Après le constat de l\\\\\\\\\\\\\\\'incident, je suis longtemps restée en pleurs. Philibert eut grand peine à me remonter le moral. Mon désespoir me poussa à un acte à la fois héroïque et insensé : je ramassa l\\\\\\\\\\\\\\\'un des singes mort et l\\\\\\\\\\\\\\\'emmena avec moi. Arrivée au camp, je le mis dans notre mini-réfrigérateur et j\\\\\\\\\\\\\\\'acheva de faire mes paquets. Philibert ne voulut point me contrarier, alors il ne prononça mot, mais je devinais sa pensée : depuis le début il me trouve insensée et bizarre, comme frappée d\\\\\\\\\\\\\\\'une folie incontrôlable, et bien sûr il fait fausse route.

	En quittant les lieux du campement, je ne pus m\\\\\\\\\\\\\\\'empêcher de repenser à ce foutu massacre. Ce que les hommes peuvent être cruels! C\\\\\\\\\\\\\\\'est vrai, on a jamais entendu parler de femmes braconnières; à cette seule pensée, j\\\\\\\\\\\\\\\'en vint à prendre Phil en aversion. Le pauvre fut tellement bouleversé par mes propos qu\\\\\\\\\\\\\\\'il s\\\\\\\\\\\\\\\'en est évanouis. Je le tenais, lui et tous les hommes du monde entier, responsable pour la disparition de plusieurs espèces et pour tout les carnages commis jusqu\\\\\\\\\\\\\\\'à ce jour. Arrivé à Santarem (sur la rive droite du fleuve Amazone), je nous pris deux billets pour Colombus (en Ohio, É-U). Avant que l\\\\\\\\\\\\\\\'avion n\\\\\\\\\\\\\\\'arrive, j\\\\\\\\\\\\\\\'eus à peine assez de temps pour m\\\\\\\\\\\\\\\'excuser et consoler Phil; après cela, ont dira que seule les femmes sont pleurnichardes, mon oeil! Ainsi en peu de temps ma peine et mes pleurs sont devenus colère et jurons envers les monstres que sont les braconniers.

	En vol, la musique retransmise à bord m\\\\\\\\\\\\\\\'apaisa à un point tel que je fini par m\\\\\\\\\\\\\\\'endormir; dans mon rêve, vraiment étrange je dois le dire, les singes de la forêt Amazonienne me prenaient pour leur déesse venue pour les sauver des méchants chasseurs, et moi innocemment je leva le bras et de ma pensée je les extermina, ainsi les braconniers n\\\\\\\\\\\\\\\'étaient plus, mais le danger rôdait toujours. C\\\\\\\\\\\\\\\'est alors que je m\\\\\\\\\\\\\\\'aperçus que j\\\\\\\\\\\\\\\'étais... Je ne le sut pas car, Phil pris d\\\\\\\\\\\\\\\'un mal de coeur, me réveilla pour m\\\\\\\\\\\\\\\'emprunter mon petit sac brun. Je ne sais pas comment il fait, mais à chaque fois qu\\\\\\\\\\\\\\\'on prend l\\\\\\\\\\\\\\\'avion ensemble, il s\\\\\\\\\\\\\\\'arrange toujours pour vomir deux fois, cela reviendrait donc à dire qu\\\\\\\\\\\\\\\'il ne supporterais pas l\\\\\\\\\\\\\\\'avion.

	De retour au pays, j\\\\\\\\\\\\\\\'extirpa le petit singe du frigo et le mis dans mon propre réfrigérateur, car c\\\\\\\\\\\\\\\'est à Phil qu\\\\\\\\\\\\\\\'appartenait le mini-frigo. Phil ne pus, une fois de plus, que renvoyer à la seule vue du petit singe mort. Après cela, nous avons remis notre travail au professeur Sparks qui nous déclara que nos diplômes n\\\\\\\\\\\\\\\'attendaient plus que sa signature pour que nous puissions nous considérer comme micro-biologistes agréés. A ma grande surprise et surtout à ma plus grande joie, sa signature ne se fit guère attendre. Peu de temps se passa avant que je ne trouve emplois à mes désirs. Phil de son côté retourna à notre ancien camp qui se situais près du Mont Alegre. Je lui promis à notre séparation coûteuse, de toujours rester en contact avec lui. Ainsi six mois plus tard, il m\\\\\\\\\\\\\\\'écrivait (c\\\\\\\\\\\\\\\'est avant l\\\\\\\\\\\\\\\'internet!) avoir contribué à l\\\\\\\\\\\\\\\'arrestation des braconniers, comme il me l\\\\\\\\\\\\\\\'avais promis. Il m\\\\\\\\\\\\\\\'écris aussi avoir croisé une drôle de jeune femme, d\\\\\\\\\\\\\\\'après ses dires, elle ressemble à une fille dont je m\\\\\\\\\\\\\\\'était fait copine au collège; de par son esprit inventif elle s\\\\\\\\\\\\\\\'attira mon amitié, et à la fin du collège, nous nous sommes quitté la larme à l\\\\\\\\\\\\\\\'oeil. J\\\\\\\\\\\\\\\'espère un jour avoir une occasion de la revoir.

	Près de trois mois passèrent avant que je ne décide de déménager au Québec, plus précisément -à- Québec. Je dus me remettre à la recherche d\\\\\\\\\\\\\\\'un emplois, j\\\\\\\\\\\\\\\'ai déjà un appartement et mon réfrigérateur était vide, alors je décida d\\\\\\\\\\\\\\\'aller à l\\\\\\\\\\\\\\\'épicerie pour le remplir.

	Sur place, tout allais bien quand, je cru reconnaître une voix que je n\\\\\\\\\\\\\\\'avais plus entendue depuis fort longtemps, une voix qui me ramena à l\\\\\\\\\\\\\\\'esprit mains moments de joie. Je me dirigea lentement vers la source, espérant arriver avant que la voix ne se taise; dans le coin des fruits et légumes je la vis, c\\\\\\\\\\\\\\\'était bien elle! La fameuse Niki Farfouil qui argumentais avec deux twit qui semblaient être jumeaux.

	Ne voulant pas me tromper, je m\\\\\\\\\\\\\\\'approcha lentement d\\\\\\\\\\\\\\\'elle et timidement je lui demanda son nom et elle confirma mes doutes. Elle ne me reconnue pas (à l\\\\\\\\\\\\\\\'époque je ne portait pas de verre correcteurs), alors je lui demanda si \\\\\\\\\\\\\\\"Véro la Gorgone\\\\\\\\\\\\\\\" lui disait quelque chose, à ces mots elle sauta et me serra dans ses bras, puis nous nous sommes mises à sauter à mains jointes. Tout le monde dans l\\\\\\\\\\\\\\\'épicerie nous regardait sautiller comme des folles. Nous avons toutes deux rougie quand nous nous en sommes aperçues.

	En sortant de là Niki me proposa de venir dîner chez elle avec les jumeaux; manquant d\\\\\\\\\\\\\\\'imagination les jumeaux ont fait du macaroni au fromage à leurs façon et ce fut délicieux. Après le repas, nous avons longuement parlé; elle me raconta sa rencontre avec un Comte Transylvanien, son aventure en Amazonie (donc c\\\\\\\\\\\\\\\'était bien elle que Philibert avais vu) et sa dernière victoire sur son éternel ennemi : Milord Dundee.


	II. Aléa jacta est

	Après cela, je lui promis de revenir la voir très bientôt et retourna chez moi. Sur le chemin du retour je repensa au petit singe qui gisait dans mon frigo, il faudrait bien que j\\\\\\\\\\\\\\\'en fasse quelque chose (en plus je ne l\\\\\\\\\\\\\\\'avais pas déclaré aux douanes, donc immigrant illégal et potentiellement source de d\\\\\\\\\\\\\\\'épidémie); soudain un idée de génie me foudroya : et si j\\\\\\\\\\\\\\\'essayais de le ramener à la vie? Pourquoi pas! Il me suffirais de réveiller son cerveau par décharges électrique et... puis non, je n\\\\\\\\\\\\\\\'ai aucune idée quant à la procédure nécessaire à cela. Je pourrais peut-être essayer de réactiver son ADN, de cette manière son cerveau suivra peut-être le retour à la vie? C\\\\\\\\\\\\\\\'est la théorie la plus folle qui m\\\\\\\\\\\\\\\'aie jamais venue à l\\\\\\\\\\\\\\\'esprit, mais comme dit si bien monsieur Lagaffe, \\\\\\\\\\\\\\\"m\\\\\\\\\\\\\\\'enfin?\\\\\\\\\\\\\\\".

	Deux semaines plus tard après maints essais, je n\\\\\\\\\\\\\\\'avais toujours pas réussi à atteindre mon but; loin de me décourager je décida de recommencer pour la ixième fois. Alors que je prélevais un autre bout de tissu, mon scalpel dérapa et je me coupa le doigt mettant fin à mes expériences. Je ne peux rien faire quand je suis blessée. J\\\\\\\\\\\\\\\'abandonne.

	Je me demande ce que devient Albert (l\\\\\\\\\\\\\\\'un des jumeaux avec Niki), peut-être devrais-je aller le voir? Je pourrais en profiter pour revoir Niki. En arrivant, c\\\\\\\\\\\\\\\'est Charles qui m\\\\\\\\\\\\\\\'a répondue : \\\\\\\\\\\\\\\"Où est Bébert?\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Dans son atelier\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Merci.\\\\\\\\\\\\\\\" J\\\\\\\\\\\\\\\'allai retrouver Albert dans son labo et je lui demanda ce qu\\\\\\\\\\\\\\\'il pensais de moi, la raison pour laquelle je voulait le savoir, c\\\\\\\\\\\\\\\'est que, voyez-vous, je suis amoureuse de lui! Il m\\\\\\\\\\\\\\\'avoua avoir un faible pour les jolies brunes aux yeux bleu, cela me plut. Charles vous surpris dans un moment de tendresse (nous nous embrassions, simplement) pour me dire que Niki voulais me voir, que veut-t\\\\\\\\\\\\\\\'elle?

	Niki me proposa un voyage en Transylvanie parce qu\\\\\\\\\\\\\\\'elle veux aller revoir son copain le Comte Von Hankens. Comme elle doit organiser le voyage, cela me donne encore trois mois (la Transylvanie ne sera pas sa seule destination), je pourrais donc reprendre mes expériences pour quelques temps.

	Comme Albert est électronicien, je lui demanda de me construire une machine qui me permettrais de réactiver une chaîne d\\\\\\\\\\\\\\\'Acide Désoxyribonucléique. Le progrès fut dès lors de la partie, chaque expérience m\\\\\\\\\\\\\\\'apportait de nouvelles solution au problème et chaque fois l\\\\\\\\\\\\\\\'ADN se réactivais un peu plus. \\\\\\\\\\\\\\\"Alors comment ça avance \\\\\\\\\\\\\\\'Vé\\\\\\\\\\\\\\\'?\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Très bien \\\\\\\\\\\\\\\'Bé\\\\\\\\\\\\\\\', je t\\\\\\\\\\\\\\\'aime.\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Moi aussi je t\\\\\\\\\\\\\\\'aime canari, dis moi j\\\\\\\\\\\\\\\'espère que t\\\\\\\\\\\\\\\'as bientôt fini parce que Anika à l\\\\\\\\\\\\\\\'intention de partir d\\\\\\\\\\\\\\\'ici trois jours pour la Transylvanie.\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Bon bien dans ce cas je vais m\\\\\\\\\\\\\\\'arrêter.\\\\\\\\\\\\\\\" Sur ces mots je me leva et m\\\\\\\\\\\\\\\'aperçus qu\\\\\\\\\\\\\\\'en prenant appui sur le bureau pour me lever, j\\\\\\\\\\\\\\\'avais mis les doigts dans la soucoupe contenant ma dernière expérimentation. \\\\\\\\\\\\\\\"Merde!\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Quoi?\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"J\\\\\\\\\\\\\\\'ai mis les doigts dedans, déjà que j\\\\\\\\\\\\\\\'aurais pas encore enlevé mes gants ça aurais été correct, mais là; ah cé pas grave, sauf que ma blessure me chauffe, je me demande pourquoi il faut toujours que je finisse par me \\\\\\\\\\\\\\\'charcuter\\\\\\\\\\\\\\\' un doigt quand l\\\\\\\\\\\\\\\'autre est guéri.\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Touche pus à tes scalpel pis prend la durée du voyage d\\\\\\\\\\\\\\\'Anika pour te reposer.\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Ok. Bon bin qu\\\\\\\\\\\\\\\'est-ce que t\\\\\\\\\\\\\\\'en dirait si tu me butinait un peu?\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Pourquoi pas?\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Viens me prendre mon petit papillon butineur!\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"J\\\\\\\\\\\\\\\'arrive!\\\\\\\\\\\\\\\"

	Après notre fulgurante dépense d\\\\\\\\\\\\\\\'énergie, Niki retontie chez moi pour me dire que nous partions plus tôt; un peu plus et elle nous surprenais nus. Je me demande ce que ça fait d\\\\\\\\\\\\\\\'être maman, j\\\\\\\\\\\\\\\'ai hâte de savoir; un chose m\\\\\\\\\\\\\\\'inquiète, quand je me suis rhabillée j\\\\\\\\\\\\\\\'ai remarquée que mes jeans étaient serrés, serais-ce à dire que j\\\\\\\\\\\\\\\'ai engraissée? A moins que je ne sois enceinte? Youpie!!

	En Transylvanie, le Compte nous acceuilla à bras ouverts. C\\\\\\\\\\\\\\\'est bien une femme de chambre, quand on as besoin d\\\\\\\\\\\\\\\'aide on n\\\\\\\\\\\\\\\'as qu\\\\\\\\\\\\\\\'à demander; vers les neuf heures je décida d\\\\\\\\\\\\\\\'aller me baigner un peu et Cassandre (c\\\\\\\\\\\\\\\'est le nom de la femme de chambre) m\\\\\\\\\\\\\\\'aida à m\\\\\\\\\\\\\\\'y rendre. Cette piscine est placée à côté du château et elle est très grande. Cassandre me laissa; je pataugeais joyeusement quand, sans raison apparente, je me senti quelque chose de poilu et de mouillé sortir de mon maillot de bain. Ma peur fut telle que je sortie de l\\\\\\\\\\\\\\\'eau à toute vitesse pour m\\\\\\\\\\\\\\\'apercevoir que j\\\\\\\\\\\\\\\'avais une queue! Je m\\\\\\\\\\\\\\\'évanouis.
[22/10/2013 : idée de changer l\\\\\\\\\\\\\\\'heure pour ~23h, un rayon bleu apparaît brièvement et la frappe, normalement c\\\\\\\\\\\\\\\'est pas un problème parce que 1. personne est dans la piscine, 2. le rayon de \\\\\\\\\\\\\\\"vampirisme\\\\\\\\\\\\\\\" ne sort pas de la salle ET 3.si ces deux premiers faits sont faux, la personne n\\\\\\\\\\\\\\\'as pas d\\\\\\\\\\\\\\\'ADN autre sur elle ou dans sa personne... donc c\\\\\\\\\\\\\\\'est le rayon de vampire qui déclenche la mutation dans une version future de l\\\\\\\\\\\\\\\'histoire! Aussi le Comte et son \\\\\\\\\\\\\\\'Igor\\\\\\\\\\\\\\\' ont fini par s\\\\\\\\\\\\\\\'apercevoir de l\\\\\\\\\\\\\\\'erreur et sont sortis quand Cassandre leur à dit que Vé est à la piscine... ou ils l\\\\\\\\\\\\\\\'y ont vue ou il part de là pour une raison... enfin il ne la trouve pas là juste comme ça par hasard!]

	Vers les minuit, le Comte me réveilla et me prêta sa cape pour rentrer à l\\\\\\\\\\\\\\\'intérieur. Il nous demanda des chocolats chauds et nous avons ensuite discuté de choses et d\\\\\\\\\\\\\\\'autres avant qu\\\\\\\\\\\\\\\'il n\\\\\\\\\\\\\\\'aille me reconduire à ma chambre et me souhaite une bonne nuit. Un quart de seconde je cru lui voir des crocs d\\\\\\\\\\\\\\\'un pouce, vivement que je me couche!

	\\\\\\\\\\\\\\\"Ah bin coup donc! J\\\\\\\\\\\\\\\'ai tu rêvé moi là?\\\\\\\\\\\\\\\" C\\\\\\\\\\\\\\\'est fou ce qu\\\\\\\\\\\\\\\'on peux imaginer quand on dort. Tiens voilà Cassandre, quoi? Si j\\\\\\\\\\\\\\\'ai bien dormis? Oui, pourquoi? Quoi! Je n\\\\\\\\\\\\\\\'ai pas rêvé, cela viendrait-il à dire que je souffre d\\\\\\\\\\\\\\\'Alzheimer? \\\\\\\\\\\\\\\"Who cares?\\\\\\\\\\\\\\\" L\\\\\\\\\\\\\\\'important c\\\\\\\\\\\\\\\'est que je ne sois pas folle.

	\\\\\\\\\\\\\\\"Bonjour monsieur le Compte, comment allez-vous?\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Ah, appelle moi donc Martin comme Niki le fait.\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Comment vas-tu?\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Bien, toi?\\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\"Bof, tsé quand tu m\\\\\\\\\\\\\\\'as réveillée?\\\\\\\\\\\\\\\" Je lui conta alors cet étrange songe que je fit avant qu\\\\\\\\\\\\\\\'il ne me trouve. Il me révéla avoir une impression de \\\\\\\\\\\\\\\"déjà vu\\\\\\\\\\\\\\\" au sujet de ce rêve.

	Une chose me chicote : comment Niki fait-elle pour forcer mon Bébert à la suivre? Quoi! J\\\\\\\\\\\\\\\'m\\\\\\\\\\\\\\\'ennuie de lui! Bon pas juste de lui, je m\\\\\\\\\\\\\\\'ennuie de son organe de plaisir aussi.

	En fin d\\\\\\\\\\\\\\\'après midi le Comte se décida enfin à me faire visiter sa bibliothèque personnelle, et elle est de taille! Aussi grande qu\\\\\\\\\\\\\\\'une bibliothèque de Collège. J\\\\\\\\\\\\\\\'investis donc le reste de ma journée dans une nouvelle que le Comte à écrit lui-même sous un nom d\\\\\\\\\\\\\\\'emprunt, c\\\\\\\\\\\\\\\'est sur l\\\\\\\\\\\\\\\'espace et ça s\\\\\\\\\\\\\\\'appelle \\\\\\\\\\\\\\\"Odyssée de l\\\\\\\\\\\\\\\'espace\\\\\\\\\\\\\\\" (un titre peu inspiré), ce que je trouve dommage c\\\\\\\\\\\\\\\'est que c\\\\\\\\\\\\\\\'est court et trop peu développé, peut-être arrangera-t\\\\\\\\\\\\\\\'il cela un jour.

	C\\\\\\\\\\\\\\\'est beau le soir, et quand le ciel revêt sa robe cosmique, je pense à lui; il m\\\\\\\\\\\\\\\'est si loin, si absent. Quand donc reviendra Niki? Même si j\\\\\\\\\\\\\\\'ai un peu peur, je vais aller me baigner, question de voir si cela se reproduira.

	Le ciel est clair, la lune brille, c\\\\\\\\\\\\\\\'est l\\\\\\\\\\\\\\\'été et il fait chaud, raison de plus pour se baigner surtout que l\\\\\\\\\\\\\\\'eau as eut le temps de se réchauffer en journée. L\\\\\\\\\\\\\\\'eau est bonne et je m\\\\\\\\\\\\\\\'ennuie toute seule, dommage que les autres habitant du château soient occupés. J\\\\\\\\\\\\\\\'ai quelques peu hâte de rencontrer Mme Von Hankens, elle n\\\\\\\\\\\\\\\'est pas revenue de sa conférence à Liverpool et monsieur le Comte s\\\\\\\\\\\\\\\'inquiète de sa femme.

	\\\\\\\\\\\\\\\"Merde!\\\\\\\\\\\\\\\" ce que je peux m\\\\\\\\\\\\\\\'ennuyer, ya... Ah! ça recommence!\\\\\\\\\\\\\\\" Mon dieu, d\\\\\\\\\\\\\\\'où peux venir cette touffe de poil qui s\\\\\\\\\\\\\\\'allonge? On dirait qu\\\\\\\\\\\\\\\'elle sort de mon maillot de bain! Au secours! Ce que je peux haïr des situations comme celle-là. Pis \\\\\\\\\\\\\\\'fuck\\\\\\\\\\\\\\\'! Je sort de l\\\\\\\\\\\\\\\'eau, j\\\\\\\\\\\\\\\'ai plus envie de savoir. Hey! J\\\\\\\\\\\\\\\'arrive pas à attraper le bord, on dirait que j\\\\\\\\\\\\\\\'ai plus de bras. [22/10/2013 : pour que ce soit plus crédible, elle devient le même singe que celui sur lequel elle as expérimenté mais version adulte et elle devient pas tellement plus petite qu\\\\\\\\\\\\\\\'elle ne l\\\\\\\\\\\\\\\'est en humain, donc une version monstre/géante du singe] Mon maillot tombe au fond de la piscine, comment j\\\\\\\\\\\\\\\'vais sortir? Non mais, comment j\\\\\\\\\\\\\\\'ai pu perdre mon maillot dans l\\\\\\\\\\\\\\\'eau? Faut que j\\\\\\\\\\\\\\\'sorte! Fiou! J\\\\\\\\\\\\\\\'ai bien faillit me noyer. Chus à genoux ou quoi? Ah! J\\\\\\\\\\\\\\\'ai rétrécie au lavage! Bon dieu, kossé qui m\\\\\\\\\\\\\\\'arrive? Ma voix, qu\\\\\\\\\\\\\\\'est-ce qui lui est arrivée? Et mes mains? C\\\\\\\\\\\\\\\'est quand même curieux, j\\\\\\\\\\\\\\\'ai l\\\\\\\\\\\\\\\'impression de ne pas rêver, et pourtant... OUCH! Non, le truc classique le confirme, je ne rêve pas; mon reflet sur l\\\\\\\\\\\\\\\'eau me fait penser à... un Sapajou! Mais... fiou, chus chanceuse, j\\\\\\\\\\\\\\\'ai pas changé de sexe. Bon comment je vais faire maintenant? C\\\\\\\\\\\\\\\'est vrai, on me chassera sûrement à cause qu\\\\\\\\\\\\\\\'on ne saura pas que c\\\\\\\\\\\\\\\'est moi et Bébert me reniera et ma carrière est finie et... ma vie aussi!
[dun dun duuuuunnn!!!]

	\\\\\\\\\\\\\\\"Bon du calme ma chère, il te faut envisager une solution pour t\\\\\\\\\\\\\\\'en tirer!\\\\\\\\\\\\\\\" C\\\\\\\\\\\\\\\'est bien de me parler à moi-même, mais ça ne règle absolument rien. Bon je suis un petit singe, je parle en petit singe et je sens le petit singe mouillé, quoi de mieux! \\\\\\\\\\\\\\\"En attendant de trouver une solution, je crois bien que je vais jouer avec ma queue, tiens, où est-t\\\\\\\\\\\\\\\'elle? Je n\\\\\\\\\\\\\\\'en ais plus, mes pieds et mon corps me sont revenu?!\\\\\\\\\\\\\\\" Je suis plus qu\\\\\\\\\\\\\\\'hébétée. Et bien, allons récupérer notre maillot de bain.

	Je vais aller me coucher à l\\\\\\\\\\\\\\\'instant, j\\\\\\\\\\\\\\\'y repenserais demain. De toutes façon, je ne compte pas laisser ce mystère sans suite ni enquête. Je devrais peut-être demander l\\\\\\\\\\\\\\\'aide du Comte? Et puis, non! Pas pour l\\\\\\\\\\\\\\\'instant. \\\\\\\\\\\\\\\"Bonne nuit Véro. Bonne nuit alter ego.\\\\\\\\\\\\\\\"

	Rien de mieux qu\\\\\\\\\\\\\\\'une bonne nuit de sommeil pour se replacer les idées. Aujourd\\\\\\\\\\\\\\\'hui je vais rester dans ma chambre pour tenter d\\\\\\\\\\\\\\\'élucider le mystère. Appelons le maître d\\\\\\\\\\\\\\\'hôtel.
	\\\\\\\\\\\\\\\"-Mademoiselle désire?
	-Déjeuner.
	-Comme d\\\\\\\\\\\\\\\'habitude?
	-Oui, sauf que je mangerais ici.
	-Bien, comme bon vous plaira.\\\\\\\\\\\\\\\"

	En attendant que ça arrive, je vais m\\\\\\\\\\\\\\\'habiller. Tiens, on dirait que mon visage est mon corps on changés; mon visage semble plus beau et mon corps aussi, je semble plus sexy. En tout cas ça confirme que chus pas enceinte, surtout que ça fait déjà trois mois que Niki est partie en Amazonie. Pis j\\\\\\\\\\\\\\\'m\\\\\\\\\\\\\\\'ennuie de mon Bébert!! Entrez! Non Cassandre, c\\\\\\\\\\\\\\\'est rien, j\\\\\\\\\\\\\\\'m\\\\\\\\\\\\\\\'ennuie de mon chum, ah mon déjeuner, met-le là, sur la petite table. Cassandre, attend! Coup donc, est-tu mariée? Avec qui? Jean-Pierre, le maître d\\\\\\\\\\\\\\\'hôtel? Ah bon! Oui tu peux disposer, merci.

	Maintenant que je suis habillée et que j\\\\\\\\\\\\\\\'ai déjeuné, mettons nous au travail. Bon, c\\\\\\\\\\\\\\\'est peut-être à cause de l\\\\\\\\\\\\\\\'eau, parce que ça fait douze fois que je vais me baigner et ça c\\\\\\\\\\\\\\\'est reproduit à chaque fois. C\\\\\\\\\\\\\\\'est peut-être la lune ou... Oui! C\\\\\\\\\\\\\\\'est peut-être ça. Chaque fois que je voyais l\\\\\\\\\\\\\\\'eau de la piscine cela me faisait penser à l\\\\\\\\\\\\\\\'immense flaque de sang dont l\\\\\\\\\\\\\\\'origine se situais au coeur des singes abattus. Et comme cela m\\\\\\\\\\\\\\\'avait profondément marquée, j\\\\\\\\\\\\\\\'y repense continuellement de façon inconsciente. Reste à savoir si je dois être dans l\\\\\\\\\\\\\\\'eau pour me transformer et d\\\\\\\\\\\\\\\'où peux bien venir ce pouvoir.

	Je passa tant de temps à chercher comment me transformer que les heures passèrent à une vitesse fulgurante et ainsi Cassandre arriva avec mon dîner sans que je n\\\\\\\\\\\\\\\'ai réellement eût le temps d\\\\\\\\\\\\\\\'avoir faim.

	Du steak, eh bien, bon enfin mangeons! Ouch! \\\\\\\\\\\\\\\"Gare\\\\\\\\\\\\\\\" ça si chus \\\\\\\\\\\\\\\"bright\\\\\\\\\\\\\\\"! J\\\\\\\\\\\\\\\'ai trouvé le moyen de me couper, encore. Mais au fait, peut-être que c\\\\\\\\\\\\\\\'est quand... quand je me suis ouvert le doigt avec mon scalpel juste avant de venir ici. Telle serais donc la solution (ou plutôt la réponse) à l\\\\\\\\\\\\\\\'énigme? Semble-t\\\\\\\\\\\\\\\'il.

	Après le souper, je me reposa une demie-heure, après quoi je me remis à mes réflexions en gardant en tête le nouveau fait. Incapable de trouver ce qui déclenche cette transformation, je décida d\\\\\\\\\\\\\\\'analyser un échantillon de mon sang; expérience douloureuse. Même si je m\\\\\\\\\\\\\\\'attendais à une réponse, je ne suspectais pas un verdict aussi clair : mon ADN était maintenant altéré!

	Vers les vingt heures, je finis par découvrir comment faire; il me suffit d\\\\\\\\\\\\\\\'y penser et voilà, c\\\\\\\\\\\\\\\'est aussi twit que ça! Pis dire que j\\\\\\\\\\\\\\\'ai tété une journée pour trouver ça! Bon enfin, fallait bin que j\\\\\\\\\\\\\\\'cherche.

	Cinq mois et toujours pas de Niki, c\\\\\\\\\\\\\\\'est à se demander si elle fait le tour du monde ou si elle m\\\\\\\\\\\\\\\'a oubliée, dans les deux cas, ça ne change rien ET JE SUIS EN MANQUE! Je crois que je vais aller me baigner pour me détendre [22/10/2013 : il commence pas à faire trop froid pour se baigner?! O\\\\\\\\\\\\\\\\_o] et j\\\\\\\\\\\\\\\'en profiterais pour renouer une fois de plus avec ma nouvelle habitude : me baigner nue sous ma forme de primate.

	Un bain de minuit, quel plaisir. C\\\\\\\\\\\\\\\'est relaxant, l\\\\\\\\\\\\\\\'eau n\\\\\\\\\\\\\\\'est ni froide ni chaude, mais tiède et éprise d\\\\\\\\\\\\\\\'un léger mouvement ondulatoire. Je me glissa hors de mon peignoir, déjà nue comme le fut la femme originelle. De mon corps élancé je fondis la surface liquide afin de m\\\\\\\\\\\\\\\'y introduire, j\\\\\\\\\\\\\\\'élue le moment suivant pour prendre une fois de plus mon corps animal. A un certain moment je me sentie comme épiée, surveillée par un oeil perçant la sombre robe de la nuit. Puis cette sensation disparue presque aussi vite. Comme à son habitude, la chauve-sourie géante entra dans le château par l\\\\\\\\\\\\\\\'une des fenêtres. Je l\\\\\\\\\\\\\\\'observait depuis environ un mois et demi, elle entre et sort toujours de cette même fenêtre, plus large que haute. Le Comte semble bien s\\\\\\\\\\\\\\\'en foutre et n\\\\\\\\\\\\\\\'en parle même pas. Je pense que je vais aller lui en parler.

	Le calme nocturne avec ses légers bruits savent calmer les plus tendus. Un bien être sublime m\\\\\\\\\\\\\\\'habite en ces moments de gloire tranquille. De nouveau je sent le regard; voulant en cerner le provenance, je sorti de l\\\\\\\\\\\\\\\'eau pour explorer les cachettes potentielles environnants la piscine. Dix minutes de recherche active me persuadèrent de mon erreur. Je retourna dans l\\\\\\\\\\\\\\\'eau, des fois j\\\\\\\\\\\\\\\'y reste jusqu\\\\\\\\\\\\\\\'à deux heures du matin à rêvasser, je rêve à mon prince charmant, au petit monde qu\\\\\\\\\\\\\\\'on pourrait construire à deux, accomplissant une fois de plus pour le bien de l\\\\\\\\\\\\\\\'humanité le miracle de la vie. [22/10/2013 : WOW! de quoi... 1991? à 2013 (+2 enfants) ça change la perspective! encore que le personnage ET l\\\\\\\\\\\\\\\'auteure sont supposées être des femmes... hahaha]

	Cette fois, ou je suis folle, ou je ne suis plus seule dans l\\\\\\\\\\\\\\\'eau, et je n\\\\\\\\\\\\\\\'ai aucun moyen d\\\\\\\\\\\\\\\'en être certaine car la lune ne présente que son quartier et n\\\\\\\\\\\\\\\'éclaire que peu la piscine, laissant la surface d\\\\\\\\\\\\\\\'un semi-jade uniforme aux rares reflets. Je vois, au fond du bassin, je vois. Une étrange forme se dessiner sous moi, elle s\\\\\\\\\\\\\\\'approche lentement, comme pour éviter d\\\\\\\\\\\\\\\'attirer l\\\\\\\\\\\\\\\'attention sur elle. Elle veut m\\\\\\\\\\\\\\\'avoir, prendre possession de ma charpente, la noyer, en extirper mon âme. Cela semble emphasé et pourtant, cela semble être son intention, m\\\\\\\\\\\\\\\'attraper. Mes réflexions m\\\\\\\\\\\\\\\'ont trahies, pendant celles-ci, la chose s\\\\\\\\\\\\\\\'était approchée, quelque centimètres me séparais maintenant du prédateur. Mais qu\\\\\\\\\\\\\\\'est-ce donc? Et pourquoi me veut-t\\\\\\\\\\\\\\\'il? Mieux! Serais-ce entré pendant que j\\\\\\\\\\\\\\\'avais le dos tourné? L\\\\\\\\\\\\\\\'ombre, elle vas me toucher, je sais au moins que c\\\\\\\\\\\\\\\'est une créature à sang chaud, car l\\\\\\\\\\\\\\\'eau se réchauffe par son approche. Ça y est, elle vas... Blub! Blub! blub!...

	\\\\\\\\\\\\\\\"-Véro, véro, réveille toi, allez debout.
	-Qu\\\\\\\\\\\\\\\'esse qui se passe?
	-Viens on vas rentrer puis on vas en discuter.
	-Niki?
	-Oui.
	-T\\\\\\\\\\\\\\\'est enfin de retour?
	-Oui!
	-T\\\\\\\\\\\\\\\'est finalement là?
	-Devine! Tsé! Enweille viens avant que t\\\\\\\\\\\\\\\'attrape froid.
	-Oui mais chus nue!
	-Bin non, t\\\\\\\\\\\\\\\'as ta robe de chambre sul\\\\\\\\\\\\\\\'dos.
	-Ah!\\\\\\\\\\\\\\\"

	A l\\\\\\\\\\\\\\\'intérieur, elle me força à aller SEULE au lit en me promettant de tout m\\\\\\\\\\\\\\\'expliquer demain; chose dite, chose due. Le lendemain elle commença à me raconter son aventure en Amazonie et comment elle avait, par miracle, échappée au piège de Sir Dundee. Mais moi ce qui m\\\\\\\\\\\\\\\'intéresse c\\\\\\\\\\\\\\\'est Bébert, mon beau Bébert! JE SUIS EN MANQUE!

	Ils sont partis au village acheter quelques petites choses dont Charles as besoin, en attendant je vais demander à Niki exactement dans quel état m\\\\\\\\\\\\\\\'avais-t\\\\\\\\\\\\\\\'elle trouvée. Chus curieuse de savoir. Pis aussi qu\\\\\\\\\\\\\\\'est-ce que c\\\\\\\\\\\\\\\'était cette foutue chose qui semble m\\\\\\\\\\\\\\\'avoir coulée pus qui m\\\\\\\\\\\\\\\'as laissée en vie? Nous nous étions parlé au déjeuner, maintenant il est presque onze heures. Je cognit à sa porte.

	\\\\\\\\\\\\\\\"-Minute!
	-Niki?
	-J\\\\\\\\\\\\\\\'ai dit minute! Oui!
	-Bin j\\\\\\\\\\\\\\\'voudrais te parler.
	-Ah, à quel sujet?
	-J\\\\\\\\\\\\\\\'peux-tu entrer avant?
	-Assied-toi.
	-C\\\\\\\\\\\\\\\'est au sujet d\\\\\\\\\\\\\\\'hier soir, j\\\\\\\\\\\\\\\'voudrais savoir...
	-Attend, j\\\\\\\\\\\\\\\'vais fermer la porte. Voilà. Oui, tu disais...
	-Comment est-ce que tu savais que j\\\\\\\\\\\\\\\'étais là?
	-Bin euh, c\\\\\\\\\\\\\\\'est Jipi qui me l\\\\\\\\\\\\\\\'as dit.
	-Bin voyons! Y sais sûrement pas que je me baigne le soir, c\\\\\\\\\\\\\\\'est une sorte de secret entre moi et Cassandre.
	-C\\\\\\\\\\\\\\\'est que.. elle lui a dit, c\\\\\\\\\\\\\\\'est ça, à ya dit.
	-Tu te cale!
	-Ok, ok, je voulais me baigner aussi, en arrivant l\\\\\\\\\\\\\\\'envie m\\\\\\\\\\\\\\\'as prise.
	-Ah oui!
	-Oui.
	-T\\\\\\\\\\\\\\\'est pas hydrophobe par hasard?
	-Pus tellement, là-bas j\\\\\\\\\\\\\\\'ai suivi une sorte de thérapie et ça marche.
	-Maintenant, dans quel état m\\\\\\\\\\\\\\\'as tu trouvée?
	-Nue, à côté de ta robe de chambre.
	-Et tu n\\\\\\\\\\\\\\\'as rien vue dans l\\\\\\\\\\\\\\\'eau?
	-Non, rien.
	-Bizarre?\\\\\\\\\\\\\\\"

	Niki me ment sûrement, même une thérapie ne l\\\\\\\\\\\\\\\'aiderais pas, de toutes façon elle hais les médicaments, alors les thérapies,sûrement pas!

	Au soir venus, je la vit descendre les escalier et traverser la porte d\\\\\\\\\\\\\\\'entrée, habillée comme elle l\\\\\\\\\\\\\\\'était, ce devais être pour aller se baigner. Je décida d\\\\\\\\\\\\\\\'étrenner mon système de sortie, il me suffit de prendre ma forme animale et de descendre le long du câblin que j\\\\\\\\\\\\\\\'ai cloué au bord de ma fenêtre pour me retrouver dans le jardin. N\\\\\\\\\\\\\\\'ayant point de vêtements (par choix) je gardis ma forme seconde pour aller épier Niki. Le chemin qu\\\\\\\\\\\\\\\'elle devais prendre s\\\\\\\\\\\\\\\'avérait plus long que le mien et j\\\\\\\\\\\\\\\'eus donc quelques précieuses secondes pour prendre cachette et position d\\\\\\\\\\\\\\\'observation.

	Peu de secondes plus tard je la vis, la lune éclairait la scène de sa face visible. Elle était nue lorsqu\\\\\\\\\\\\\\\'elle retira son peignoir pour pénétrer l\\\\\\\\\\\\\\\'eau, plusieurs minutes passèrent sans que la surface ne fût animée de nouveau par ces ondes que produisent les corps étranger à sa nature.

	La curiosité me poussa à m\\\\\\\\\\\\\\\'approcher pour voir ce qui s\\\\\\\\\\\\\\\'y passe; au fond de la piscine une vague forme glissais. Cette forme était en tout point semblable à celle qui m\\\\\\\\\\\\\\\'avait attaquée, cela viendrait à dire que Niki fut attrapée à son tour par la \\\\\\\\\\\\\\\"chose\\\\\\\\\\\\\\\"; pourtant, il n\\\\\\\\\\\\\\\'y as aucune trace d\\\\\\\\\\\\\\\'elle dans la piscine, ni les environs.

	Encore un mois avant d\\\\\\\\\\\\\\\'accoucher, le docteur et sa femme vont venir me chercher tout a l\\\\\\\\\\\\\\\'heure, je vais passer le reste de ma grossesse chez eux en pension, comme ça, ça vas être un peu moins stressant pour tout le monde.

	A deux semaines et demie de mon accouchement, Albert est venu m\\\\\\\\\\\\\\\'annoncer que Niki avait décidée d\\\\\\\\\\\\\\\'aller éclaircir le mystère de \\\\\\\\\\\\\\\"l\\\\\\\\\\\\\\\'homme de Pékin\\\\\\\\\\\\\\\". Ça vas bien, y sera pas là pour la naissance de son enfant! Et bin, à l\\\\\\\\\\\\\\\'aurais pus attendre un peu toute bin que l\\\\\\\\\\\\\\\'enfant soit né. Enfin, comme ça, ça lui changera les idées et moi je réfléchirais au nom du bébé.

	Quelques minutes avant que le bébé ne soit sorti, j\\\\\\\\\\\\\\\'avais comme perdu contact avec la réalité; quand le docteur me réveilla, il me dit être à la fois désolé et bien heureux, désolé parce qu\\\\\\\\\\\\\\\'il m\\\\\\\\\\\\\\\'avait administré un sédatif au lieu d\\\\\\\\\\\\\\\'un anti-douleur et heureux de m\\\\\\\\\\\\\\\'annoncer que mes jumelles et mon garçon allaient bien et étaient en santé. Étonnée je lui avais demandé \\\\\\\\\\\\\\\"Mais qu\\\\\\\\\\\\\\\'est-ce que cette histoire?\\\\\\\\\\\\\\\" Et lui de me répondre que l\\\\\\\\\\\\\\\'infirmière, en poussant sur mon ventre pour aider, avait senti trois bosses plutôt qu\\\\\\\\\\\\\\\'une, estomaqué il incita l\\\\\\\\\\\\\\\'infirmière à continuer de pousser; un, deux puis trois petits bout de choux sortirent précipitamment, il les regarda, tous trois alignés sur la petite table au pied du lit d\\\\\\\\\\\\\\\'accouchement toujours reliés à leur mère. La surprise passée, il entreprit de couper les cordons, ce qu\\\\\\\\\\\\\\\'il accompli de main de maître, lui qui, comme son père et cinq générations le précédant, avais mis et vu mettre au monde les trois quart du village sans jamais avoir assisté à un tel événement, fut plus qu\\\\\\\\\\\\\\\'honoré d\\\\\\\\\\\\\\\'en avoir été à la fois spectateur et acteur. De retour sur terre, je demanda à les voir et l\\\\\\\\\\\\\\\'infirmière me les amena, tout trois emmitouflés dans leurs premiers vêtements les uns à côté des autres sur une table à roulette aménagée en mini-lit roulant. Devant ce spectacle, je pleura, trois enfants! Trois. Comme les mousquetaires, amis de Dartagnan. Trois. Un bonheur triple à celui tant escompté. Bébert et les autres vont sûrement \\\\\\\\\\\\\\\"en tomber en bas de leurs bas!\\\\\\\\\\\\\\\", comme dit Niki, tout comme j\\\\\\\\\\\\\\\'ai faillit tomber en bas de mon lit tout à l\\\\\\\\\\\\\\\'heure.

	Les petits ont maintenant trois mois (les pires 90 jours de ma vie, j\\\\\\\\\\\\\\\'ai pas dormi et mes seins en ont souffert, ils ont perdu de leur fermetés, vive les bouteilles), je suis retournée au château deux semaines après l\\\\\\\\\\\\\\\'accouchement, les chéris me prennent tout mon temps, et encore! Cassandre dois m\\\\\\\\\\\\\\\'aider, sinon j\\\\\\\\\\\\\\\'en décaperais les murs si je n\\\\\\\\\\\\\\\'avais pas d\\\\\\\\\\\\\\\'aide. Enfin, ont se débrouille très bien; j\\\\\\\\\\\\\\\'ai convoqué le prêtre pour les faire baptiser, mais je ne leur ais toujours pas trouvé de noms. [23/10/2013 : Au Qc on as 29 jours pour se décider... 90+ en Transylvanie? Hahaha!!!]

	Après une longue réflexion (et juste à temps pour le baptême), je les ais nommés Clara, Luc et Jacinthe (un gars et deux filles; drôle d\\\\\\\\\\\\\\\'idée mais enfin). Ils sont un peu plus sage maintenant, ce qui vas me permettre de chercher l\\\\\\\\\\\\\\\'explication de mon pouvoir de transformation (que j\\\\\\\\\\\\\\\'avais perdu dès le début de ma grossesse et que je viens à peine de revoir).

{{ Le manuscrit arrête ici. }}";

echo decode($chaine);